pages:
  stage: deploy
  image: ghcr.io/l-trump/logseq-publish-spa:alpine
  variables:
    PUB_GRAPH_DIR: $CI_PROJECT_DIR
    PUB_OUT_DIR: $CI_PROJECT_DIR/public
  script:
    - /opt/entrypoint.sh
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'